package io.gauss.lex.compliance;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Downloadable proof that all personal data linked to a data subject was
 * deleted (GDPR Article 17 — right to erasure, HU-051).
 *
 * <p>The certificate is generated by {@link ComplianceService#deleteSubject}
 * after the deletion completes.  It can be provided to Data Protection
 * Officers or regulators as evidence.
 *
 * @param certificateId    unique ID of this certificate
 * @param subjectId        the data subject identifier that was erased
 * @param deletedAt        wall-clock time of the deletion
 * @param deletedDataTypes list of data categories that were erased
 * @param totalRecords     total number of individual records deleted
 */
public record DeletionCertificate(
        String       certificateId,
        String       subjectId,
        Instant      deletedAt,
        List<String> deletedDataTypes,
        int          totalRecords
) {

    public DeletionCertificate {
        deletedDataTypes = List.copyOf(deletedDataTypes);
    }

    /** Factory that generates a fresh UUID-based certificate ID. */
    public static DeletionCertificate of(String subjectId,
                                          List<String> dataTypes,
                                          int records) {
        return new DeletionCertificate(
                UUID.randomUUID().toString(),
                subjectId,
                Instant.now(),
                dataTypes,
                records);
    }

    /**
     * Returns a plain-text certificate body suitable for PDF generation or
     * email attachment.
     */
    public String toText() {
        return String.format(
                """
                DATA ERASURE CERTIFICATE
                ========================
                Certificate ID : %s
                Subject ID     : %s
                Deleted at     : %s
                Data types     : %s
                Total records  : %d

                This certificate confirms that all personal data linked to the
                above subject identifier has been permanently and irreversibly
                deleted from all Gauss framework data stores, in accordance with
                GDPR Article 17 (right to erasure).
                """,
                certificateId, subjectId, deletedAt,
                String.join(", ", deletedDataTypes), totalRecords);
    }
}
