package io.gauss.augur.llm;

import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * Accumulates {@link TokenUsage} records across all LLM endpoint calls and
 * exposes aggregated statistics per endpoint (HU-058).
 *
 * <p>This tracker is a lightweight in-process store.  For production deployments
 * the data should be flushed to a time-series database or metrics backend.
 *
 * <p>Usage:
 * <pre>{@code
 * TokenUsageTracker tracker = new TokenUsageTracker();
 * tracker.record(TokenUsage.of(500, 200, "openai", "gpt-4o", "chatbot"));
 *
 * long totalInput = tracker.totalInputTokens("chatbot");
 * double cost     = tracker.totalCostUsd("chatbot", new LLMCostEstimator());
 * }</pre>
 */
public final class TokenUsageTracker {

    private final CopyOnWriteArrayList<TokenUsage> usages = new CopyOnWriteArrayList<>();
    private final LLMCostEstimator costEstimator;

    public TokenUsageTracker() {
        this(new LLMCostEstimator());
    }

    public TokenUsageTracker(LLMCostEstimator costEstimator) {
        this.costEstimator = costEstimator;
    }

    // -------------------------------------------------------------------------
    // Recording
    // -------------------------------------------------------------------------

    /**
     * Records a token usage snapshot.
     *
     * @param usage the usage to record (must not be {@code null})
     */
    public void record(TokenUsage usage) {
        usages.add(usage);
    }

    // -------------------------------------------------------------------------
    // Aggregation
    // -------------------------------------------------------------------------

    /**
     * Returns all recorded usages for the given endpoint, in recording order.
     */
    public List<TokenUsage> findByEndpoint(String endpointName) {
        return usages.stream()
                .filter(u -> u.endpointName().equals(endpointName))
                .toList();
    }

    /** Returns all recorded usages regardless of endpoint. */
    public List<TokenUsage> findAll() {
        return List.copyOf(usages);
    }

    /** Total input tokens consumed by the given endpoint. */
    public long totalInputTokens(String endpointName) {
        return findByEndpoint(endpointName).stream()
                .mapToLong(TokenUsage::inputTokens).sum();
    }

    /** Total output tokens generated by the given endpoint. */
    public long totalOutputTokens(String endpointName) {
        return findByEndpoint(endpointName).stream()
                .mapToLong(TokenUsage::outputTokens).sum();
    }

    /** Total tokens (input + output) consumed by the given endpoint. */
    public long totalTokens(String endpointName) {
        return totalInputTokens(endpointName) + totalOutputTokens(endpointName);
    }

    /**
     * Estimated total cost in USD for the given endpoint, using the configured
     * {@link LLMCostEstimator}.
     */
    public double totalCostUsd(String endpointName) {
        return findByEndpoint(endpointName).stream()
                .mapToDouble(costEstimator::estimateCostUsd)
                .sum();
    }

    /** Number of recorded calls for the given endpoint. */
    public long callCount(String endpointName) {
        return findByEndpoint(endpointName).size();
    }

    /** Number of recorded calls across all endpoints. */
    public long totalCallCount() {
        return usages.size();
    }

    /**
     * Returns {@code true} when the total estimated cost for {@code endpointName}
     * has reached or exceeded {@code budgetUsd * alertFraction}.
     *
     * @param endpointName  the endpoint to check
     * @param budgetUsd     monthly spending limit in USD
     * @param alertFraction fraction of the budget that triggers an alert (e.g., 0.8)
     */
    public boolean isBudgetAlertTriggered(String endpointName,
                                           double budgetUsd,
                                           double alertFraction) {
        return totalCostUsd(endpointName) >= budgetUsd * alertFraction;
    }

    /** Removes all recorded usages (intended for tests). */
    public void clear() {
        usages.clear();
    }
}
