package io.gauss.vela.generator;

import java.util.List;

/**
 * Generates the {@code index.ts} barrel file that re-exports all endpoint modules.
 */
public final class BarrelGenerator {

    public static final BarrelGenerator INSTANCE = new BarrelGenerator();

    private BarrelGenerator() {}

    /** Generates barrel content from a list of {@code .ts} file names (or base names). */
    public String generate(List<String> fileNames) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by Gauss Vela — do not edit manually\n\n");
        for (String name : fileNames) {
            String base = name.endsWith(".ts") ? name.substring(0, name.length() - 3) : name;
            sb.append("export * from './").append(base).append("';\n");
        }
        return sb.toString();
    }

    /** Convenience overload: derives file names from endpoint classes via the generator. */
    public String generate(List<Class<?>> endpointClasses, ClientFunctionGenerator gen) {
        return generate(endpointClasses.stream().map(gen::fileName).toList());
    }
}
