package io.gauss.vela.generator;

import io.gauss.vela.model.EndpointMethod;
import io.gauss.vela.model.TsParameter;
import io.gauss.vela.scanner.EndpointScanner;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates a TypeScript client file for a single {@code @MLEndpoint} class.
 *
 * <p>Each public method becomes an {@code async} function. Server errors are
 * raised as a typed {@code GaussApiError}. The output is a self-contained
 * {@code .ts} module ready to be placed in {@code frontend/generated/}.
 */
public final class ClientFunctionGenerator {

    private static final String HEADER =
            "// Auto-generated by Gauss Vela — do not edit manually\n";

    private static final String ERROR_CLASS = """
            export class GaussApiError extends Error {
              constructor(
                public readonly status: number,
                message: string,
              ) {
                super(message);
                this.name = 'GaussApiError';
              }
            }
            """;

    private final EndpointScanner scanner;

    public ClientFunctionGenerator() {
        this(new EndpointScanner());
    }

    ClientFunctionGenerator(EndpointScanner scanner) {
        this.scanner = scanner;
    }

    /** Returns the {@code .ts} file name for the given endpoint class. */
    public String fileName(Class<?> endpointClass) {
        return endpointClass.getSimpleName() + ".ts";
    }

    /** Generates the full TypeScript source for one endpoint class. */
    public String generate(Class<?> endpointClass) {
        List<EndpointMethod> methods = scanner.scan(endpointClass);

        StringBuilder sb = new StringBuilder();
        sb.append(HEADER).append('\n');
        sb.append(ERROR_CLASS).append('\n');

        for (EndpointMethod m : methods) {
            sb.append(renderFunction(m)).append('\n');
        }

        return sb.toString().stripTrailing() + '\n';
    }

    // -------------------------------------------------------------------------

    private String renderFunction(EndpointMethod m) {
        String paramList = m.parameters().stream()
                .map(TsParameter::render)
                .collect(Collectors.joining(", "));

        String returnTs   = m.returnType().render();
        String promiseRet = returnTs.equals("void") ? "Promise<void>" : "Promise<" + returnTs + ">";

        StringBuilder sb = new StringBuilder();
        sb.append("/**\n");
        sb.append(" * ").append(m.httpMethod()).append(' ').append(m.path()).append('\n');
        sb.append(" */\n");
        sb.append("export async function ").append(m.name())
          .append('(').append(paramList).append("): ").append(promiseRet).append(" {\n");

        if (m.httpMethod().equals("GET")) {
            sb.append("  const response = await fetch('").append(m.path()).append("');\n");
        } else {
            String body = m.parameters().isEmpty() ? "{}" : m.parameters().get(0).name();
            sb.append("  const response = await fetch('").append(m.path()).append("', {\n");
            sb.append("    method: 'POST',\n");
            sb.append("    headers: { 'Content-Type': 'application/json' },\n");
            sb.append("    body: JSON.stringify(").append(body).append("),\n");
            sb.append("  });\n");
        }

        sb.append("  if (!response.ok) {\n");
        sb.append("    throw new GaussApiError(response.status, await response.text());\n");
        sb.append("  }\n");

        if (returnTs.equals("void")) {
            sb.append('}');
        } else {
            sb.append("  return response.json() as Promise<").append(returnTs).append(">();\n");
            sb.append('}');
        }

        return sb.toString();
    }
}
