package io.gauss.vela.generator;

import io.gauss.vela.model.EndpointMethod;
import io.gauss.vela.model.TsParameter;
import io.gauss.vela.scanner.EndpointScanner;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Generates a TypeScript client file for a single {@code @MLEndpoint} class.
 *
 * <p>Each public method becomes an {@code async} function. Server errors are
 * raised as a typed {@code GaussApiError}. The output is a self-contained
 * {@code .ts} module ready to be placed in {@code frontend/generated/}.
 */
public final class ClientFunctionGenerator {

    private static final String HEADER =
            "// Auto-generated by Gauss Vela — do not edit manually\n";

    private static final String ERROR_CLASS = """
            export class GaussApiError extends Error {
              constructor(
                public readonly status: number,
                message: string,
              ) {
                super(message);
                this.name = 'GaussApiError';
              }
            }
            """;

    /**
     * Auth token interceptor (HU-031 AC-4).
     * Customize {@code getToken()} to fit your auth provider
     * (localStorage, cookie, in-memory store, etc.).
     */
    private static final String AUTH_INTERCEPTOR = """
            // ── Auth interceptor (HU-031) ────────────────────────────────────────
            // Replace getToken() with your own token source if needed.
            function getToken(): string | null {
              return typeof localStorage !== 'undefined'
                ? localStorage.getItem('gauss.token')
                : null;
            }

            async function authFetch(url: string, init?: RequestInit): Promise<Response> {
              const token = getToken();
              const headers = new Headers(init?.headers);
              if (token) headers.set('Authorization', `Bearer ${token}`);
              return fetch(url, { ...init, headers });
            }
            """;

    private final EndpointScanner scanner;

    public ClientFunctionGenerator() {
        this(new EndpointScanner());
    }

    ClientFunctionGenerator(EndpointScanner scanner) {
        this.scanner = scanner;
    }

    /** Returns the {@code .ts} file name for the given endpoint class. */
    public String fileName(Class<?> endpointClass) {
        return endpointClass.getSimpleName() + ".ts";
    }

    /** Generates the full TypeScript source for one endpoint class. */
    public String generate(Class<?> endpointClass) {
        List<EndpointMethod> methods = scanner.scan(endpointClass);

        StringBuilder sb = new StringBuilder();
        sb.append(HEADER).append('\n');
        sb.append(ERROR_CLASS).append('\n');
        sb.append(AUTH_INTERCEPTOR).append('\n');

        for (EndpointMethod m : methods) {
            sb.append(renderFunction(m)).append('\n');
        }

        return sb.toString().stripTrailing() + '\n';
    }

    // -------------------------------------------------------------------------

    private String renderFunction(EndpointMethod m) {
        if (m.reactiveKind().isStreaming()) return renderStreamingFunction(m);
        return renderPromiseFunction(m);
    }

    private String renderPromiseFunction(EndpointMethod m) {
        String paramList = m.parameters().stream()
                .map(TsParameter::render)
                .collect(Collectors.joining(", "));

        String returnTs   = m.returnType().render();
        String promiseRet = returnTs.equals("void") ? "Promise<void>" : "Promise<" + returnTs + ">";

        StringBuilder sb = new StringBuilder();
        sb.append("/**\n");
        sb.append(" * ").append(m.httpMethod()).append(' ').append(m.path()).append('\n');
        sb.append(" */\n");
        sb.append("export async function ").append(m.name())
          .append('(').append(paramList).append("): ").append(promiseRet).append(" {\n");

        if (m.httpMethod().equals("GET")) {
            sb.append("  const response = await authFetch('").append(m.path()).append("');\n");
        } else {
            String body = m.parameters().isEmpty() ? "{}" : m.parameters().get(0).name();
            sb.append("  const response = await authFetch('").append(m.path()).append("', {\n");
            sb.append("    method: 'POST',\n");
            sb.append("    headers: { 'Content-Type': 'application/json' },\n");
            sb.append("    body: JSON.stringify(").append(body).append("),\n");
            sb.append("  });\n");
        }

        sb.append("  if (!response.ok) {\n");
        sb.append("    throw new GaussApiError(response.status, await response.text());\n");
        sb.append("  }\n");

        if (returnTs.equals("void")) {
            sb.append('}');
        } else {
            sb.append("  return response.json() as Promise<").append(returnTs).append(">();\n");
            sb.append('}');
        }

        return sb.toString();
    }

    /**
     * Generates an {@code AsyncIterable<T>} function backed by Server-Sent Events.
     * The caller can cancel the stream via {@code AbortController}.
     */
    private String renderStreamingFunction(EndpointMethod m) {
        String paramList = m.parameters().stream()
                .map(TsParameter::render)
                .collect(Collectors.joining(", "));
        String sep        = paramList.isEmpty() ? "" : ", ";
        String elementTs  = m.returnType().render();

        return """
                /**
                 * %s %s (SSE stream → AsyncIterable<%s>)
                 */
                export async function* %s(%ssignal?: AbortSignal): AsyncIterable<%s> {
                  const response = await authFetch('%s', { signal });
                  if (!response.ok) {
                    throw new GaussApiError(response.status, await response.text());
                  }
                  const reader = response.body!.getReader();
                  const decoder = new TextDecoder();
                  let buffer = '';
                  try {
                    while (true) {
                      const { done, value } = await reader.read();
                      if (done) break;
                      buffer += decoder.decode(value, { stream: true });
                      const lines = buffer.split('\\n');
                      buffer = lines.pop() ?? '';
                      for (const line of lines) {
                        if (line.startsWith('data: ')) {
                          yield JSON.parse(line.slice(6)) as %s;
                        }
                      }
                    }
                  } finally {
                    reader.releaseLock();
                  }
                }""".formatted(
                m.httpMethod(), m.path(), elementTs,
                m.name(), paramList + sep,
                elementTs,
                m.path(),
                elementTs);
    }
}
