package io.gauss.vela.generator;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

/**
 * Generates a Zod schema file from a Java DTO class, mirroring Jakarta Bean
 * Validation constraints ({@code @NotNull}, {@code @Min}, {@code @Max},
 * {@code @Email}, {@code @Size}, {@code @Pattern}).
 *
 * <p>Output includes:
 * <ul>
 *   <li>A React Hook Form integration snippet as a header comment.</li>
 *   <li>{@code export const XxxSchema = z.object({...})} — the Zod schema.</li>
 *   <li>{@code export type Xxx = z.infer<typeof XxxSchema>} — the derived TS type.</li>
 * </ul>
 */
public final class ZodSchemaGenerator {

    public static final ZodSchemaGenerator INSTANCE = new ZodSchemaGenerator();

    private ZodSchemaGenerator() {}

    /** Returns the {@code .ts} file name for the given DTO class. */
    public String fileName(Class<?> dtoClass) {
        return dtoClass.getSimpleName() + "Schema.ts";
    }

    public String generate(Class<?> dtoClass) {
        String name = dtoClass.getSimpleName();
        List<String> fieldLines = new ArrayList<>();

        for (Field field : dtoClass.getDeclaredFields()) {
            if (Modifier.isStatic(field.getModifiers())) continue;
            fieldLines.add("  " + field.getName() + ": " + zodExpr(field) + ",");
        }

        return """
                // Auto-generated by Gauss Vela — do not edit manually
                //
                // React Hook Form integration:
                //   import { useForm } from 'react-hook-form';
                //   import { zodResolver } from '@hookform/resolvers/zod';
                //   import { %1$sSchema, type %1$s } from './%1$sSchema';
                //
                //   const { register, handleSubmit } = useForm<%1$s>({
                //     resolver: zodResolver(%1$sSchema),
                //   });

                import { z } from 'zod';

                export const %1$sSchema = z.object({
                %2$s
                });

                export type %1$s = z.infer<typeof %1$sSchema>;
                """.formatted(name, String.join("\n", fieldLines));
    }

    // -------------------------------------------------------------------------

    private String zodExpr(Field field) {
        String base = zodBaseType(field.getGenericType());
        return applyConstraints(base, field);
    }

    private String zodBaseType(Type type) {
        if (type instanceof Class<?> cls) {
            if (cls == String.class || cls == char.class || cls == Character.class)
                return "z.string()";
            if (isNumberClass(cls)) return "z.number()";
            if (cls == boolean.class || cls == Boolean.class) return "z.boolean()";
            if (cls.isEnum()) return "z.nativeEnum(" + cls.getSimpleName() + ")";
            return "z.object({})";
        }
        if (type instanceof ParameterizedType pt) {
            Class<?> raw = (Class<?>) pt.getRawType();
            Type[] args  = pt.getActualTypeArguments();
            if (Optional.class.isAssignableFrom(raw) && args.length == 1)
                return zodBaseType(args[0]) + ".optional()";
            if (Collection.class.isAssignableFrom(raw) && args.length == 1)
                return "z.array(" + zodBaseType(args[0]) + ")";
        }
        return "z.unknown()";
    }

    private String applyConstraints(String expr, Field field) {
        StringBuilder sb = new StringBuilder(expr);
        for (Annotation ann : field.getAnnotations()) {
            String simple = ann.annotationType().getSimpleName();
            switch (simple) {
                case "NotNull"  -> { if (expr.startsWith("z.string")) sb.append(".min(1)"); }
                case "Email"    -> { if (expr.startsWith("z.string")) sb.append(".email()"); }
                case "Nullable" -> sb.append(".nullable()");
                case "Min"      -> sb.append(".min(").append(longValue(ann, "value")).append(')');
                case "Max"      -> sb.append(".max(").append(longValue(ann, "value")).append(')');
                case "Size"     -> {
                    int min = intValue(ann, "min");
                    int max = intValue(ann, "max");
                    if (min > 0)                        sb.append(".min(").append(min).append(')');
                    if (max < Integer.MAX_VALUE)        sb.append(".max(").append(max).append(')');
                }
                case "Pattern"  -> {
                    String regexp = stringValue(ann, "regexp");
                    if (!regexp.isEmpty())
                        sb.append(".regex(new RegExp('").append(regexp.replace("'", "\\'")).append("'))");
                }
            }
        }
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // Reflection helpers for annotation attribute values
    // -------------------------------------------------------------------------

    private static long longValue(Annotation ann, String method) {
        try { return (long) ann.annotationType().getMethod(method).invoke(ann); }
        catch (Exception e) { return 0; }
    }

    private static int intValue(Annotation ann, String method) {
        try { return (int) ann.annotationType().getMethod(method).invoke(ann); }
        catch (Exception e) { return 0; }
    }

    private static String stringValue(Annotation ann, String method) {
        try { return (String) ann.annotationType().getMethod(method).invoke(ann); }
        catch (Exception e) { return ""; }
    }

    private static boolean isNumberClass(Class<?> cls) {
        return cls == byte.class  || cls == Byte.class    ||
               cls == short.class || cls == Short.class   ||
               cls == int.class   || cls == Integer.class ||
               cls == long.class  || cls == Long.class    ||
               cls == float.class || cls == Float.class   ||
               cls == double.class|| cls == Double.class;
    }
}
