package io.gauss.vela.generator;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Covers HU-007 AC-5: index.ts barrel re-exports all endpoint modules.
 */
class BarrelGeneratorTest {

    private final BarrelGenerator gen = BarrelGenerator.INSTANCE;

    @Test
    void barrel_containsAutoGeneratedHeader() {
        String ts = gen.generate(List.of("ChurnEndpoint.ts"));
        assertThat(ts).startsWith("// Auto-generated by Gauss Vela");
    }

    @Test
    void barrel_reExportsEachFile() {
        String ts = gen.generate(List.of("ChurnEndpoint.ts", "GreetingEndpoint.ts"));
        assertThat(ts).contains("export * from './ChurnEndpoint';");
        assertThat(ts).contains("export * from './GreetingEndpoint';");
    }

    @Test
    void barrel_stripsExtensionFromFileNames() {
        String ts = gen.generate(List.of("UserEndpoint.ts"));
        assertThat(ts).contains("export * from './UserEndpoint';");
        assertThat(ts).doesNotContain(".ts';");
    }

    @Test
    void barrel_acceptsBaseNamesWithoutExtension() {
        String ts = gen.generate(List.of("OrderEndpoint"));
        assertThat(ts).contains("export * from './OrderEndpoint';");
    }

    @Test
    void barrel_emptyList_producesHeaderOnly() {
        String ts = gen.generate(List.of());
        assertThat(ts.trim()).isEqualTo("// Auto-generated by Gauss Vela — do not edit manually");
    }
}
